---
plugin: amazon.aws.aws_ec2

regions:
- eu-north-1

filters:
  "tag:env": dev
  instance-state-name: running

compose:
  ansible_host: public_ip_address

keyed_groups:
- key: tags.Name
  prefix: name
- key: tags.env
  prefix: env
